"""
PDF Generator Utility for WhatsApp Antigravity Bot
Creates clean, professional, publication-quality PDFs from text or markdown prompts.
"""

import sys
import os
import argparse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
import re

# Custom Canvas for dynamic 'Page X of Y' and Running Headers
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (on pages > 1)
        if self._pageNumber > 1:
            self.drawString(45, 755, "⚡ ANTIGRAVITY AI • EXECUTIVE REPORT & STUDY MASTER")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(45, 748, 567, 748)

        # Footer
        self.drawString(45, 28, "Generated by Antigravity Autonomous Agentic AI System")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(567, 28, page_str)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(45, 40, 567, 40)
        
        self.restoreState()

# Register a font with wide Unicode support if available
FONT_NAME = 'Helvetica'
BOLD_FONT_NAME = 'Helvetica-Bold'

for p in [
    '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    'C:/Windows/Fonts/arial.ttf',
    'C:/Windows/Fonts/segoeui.ttf'
]:
    if os.path.exists(p):
        try:
            pdfmetrics.registerFont(TTFont('UniversalFont', p))
            FONT_NAME = 'UniversalFont'
            BOLD_FONT_NAME = 'UniversalFont'
            break
        except Exception:
            pass

def clean_text_for_font(text: str, font: str) -> str:
    if font == 'Helvetica' or font == 'Helvetica-Bold':
        # Remove characters outside latin-1 to avoid ReportLab encoding crash
        return text.encode('latin-1', 'replace').decode('latin-1')
    return text

def create_pdf(output_path: str, title: str, content: str, subtitle: str = "Generated by Antigravity AI"):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=BOLD_FONT_NAME,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )

    h1_style = ParagraphStyle(
        'DocH1',
        parent=styles['Heading1'],
        fontName=BOLD_FONT_NAME,
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=14,
        spaceAfter=6
    )

    h2_style = ParagraphStyle(
        'DocH2',
        parent=styles['Heading2'],
        fontName=BOLD_FONT_NAME,
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=10,
        spaceAfter=4
    )

    h3_style = ParagraphStyle(
        'DocH3',
        parent=styles['Heading3'],
        fontName=BOLD_FONT_NAME,
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#0284C7'),
        spaceBefore=8,
        spaceAfter=3
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'DocBullet',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        leftIndent=15,
        spaceAfter=4
    )

    callout_style = ParagraphStyle(
        'DocCallout',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#1E293B'),
        leftIndent=15,
        spaceBefore=4,
        spaceAfter=6
    )

    import re

    def format_inline_markdown(text: str) -> str:
        # 1. Clean math LaTeX symbols
        cleaned = text.replace('^2', '²').replace('^3', '³').replace('^n', 'ⁿ')
        cleaned = cleaned.replace(r'\times', '×').replace(r'\div', '÷').replace(r'\pm', '±')
        cleaned = cleaned.replace(r'\le', '≤').replace(r'\ge', '≥').replace(r'\approx', '≈')
        cleaned = cleaned.replace(r'\neq', '≠').replace(r'\infty', '∞').replace(r'\pi', 'π')
        cleaned = re.sub(r'\$\$(.*?)\$\$', r'<b>\1</b>', cleaned)
        cleaned = re.sub(r'\$(.*?)\$', r'\1', cleaned)

        # 2. XML escape
        t = cleaned.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        # 3. Bold: **bold**
        t = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', t)
        # 4. Italic: *italic*
        t = re.sub(r'(?<!\*)\*(?!\*)(.*?)\*', r'<i>\1</i>', t)
        # 5. Inline code: `code`
        t = re.sub(r'`(.*?)`', r'<font face="Courier" color="#0369a1">\1</font>', t)
        return t

    story = []

    # Title & Subtitle
    safe_title = clean_text_for_font(title, BOLD_FONT_NAME)
    safe_sub = clean_text_for_font(subtitle, FONT_NAME)
    story.append(Paragraph(safe_title, title_style))
    story.append(Paragraph(safe_sub, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284C7'), spaceAfter=12))

    # Parse content lines
    lines = content.split('\n')
    i = 0
    total_lines = len(lines)

    while i < total_lines:
        line = lines[i].strip()
        if not line:
            story.append(Spacer(1, 4))
            i += 1
            continue

        clean_line = clean_text_for_font(line, FONT_NAME)

        # Check for Markdown Table: starts and ends with |
        if clean_line.startswith('|') and clean_line.endswith('|'):
            table_rows = []
            while i < total_lines and lines[i].strip().startswith('|') and lines[i].strip().endswith('|'):
                cur_row = lines[i].strip()
                # Ignore separator lines like |---|---|
                if not re.match(r'^\|[\s\-:|]+\|$', cur_row):
                    cols = [c.strip() for c in cur_row.strip('|').split('|')]
                    formatted_cols = [Paragraph(format_inline_markdown(clean_text_for_font(c, FONT_NAME)), body_style) for c in cols]
                    table_rows.append(formatted_cols)
                i += 1
            
            if table_rows:
                try:
                    t = Table(table_rows, colWidths=None)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
                        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
                        ('TOPPADDING', (0, 0), (-1, -1), 4),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 6))
                except Exception:
                    pass
            continue

        # Headings
        if clean_line.startswith('# '):
            story.append(Paragraph(format_inline_markdown(clean_line[2:].strip()), h1_style))
        elif clean_line.startswith('## '):
            story.append(Paragraph(format_inline_markdown(clean_line[3:].strip()), h2_style))
        elif clean_line.startswith('### '):
            story.append(Paragraph(format_inline_markdown(clean_line[4:].strip()), h3_style))
        elif clean_line.startswith('#### '):
            story.append(Paragraph(f"<b>{format_inline_markdown(clean_line[5:].strip())}</b>", body_style))
        # Bullet points
        elif clean_line.startswith('- ') or clean_line.startswith('* ') or clean_line.startswith('• '):
            clean_bullet = clean_line[2:].strip()
            story.append(Paragraph(f"• {format_inline_markdown(clean_bullet)}", bullet_style))
        # Numbered lists like 1. 2.
        elif re.match(r'^\d+\.\s', clean_line):
            story.append(Paragraph(format_inline_markdown(clean_line), bullet_style))
        # Callout block: > Note / > Tip / > Warning
        elif clean_line.startswith('> '):
            callout_text = clean_line[2:].strip()
            callout_p = Paragraph(f"💡 <b>IMPORTANT / EXAM HACK:</b><br/>{format_inline_markdown(callout_text)}", callout_style)
            try:
                callout_table = Table([[callout_p]], colWidths=[522])
                callout_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
                    ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                    ('LINELEFT', (0,0), (0,-1), 3.5, colors.HexColor('#0284C7')),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('LEFTPADDING', (0,0), (-1,-1), 10),
                    ('RIGHTPADDING', (0,0), (-1,-1), 10),
                ]))
                story.append(callout_table)
                story.append(Spacer(1, 4))
            except Exception:
                story.append(callout_p)
        else:
            story.append(Paragraph(format_inline_markdown(clean_line), body_style))

        i += 1

    story.append(Spacer(1, 15))
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate PDF document")
    parser.add_argument("--out", required=True, help="Output PDF file path")
    parser.add_argument("--title", required=True, help="Title of the PDF")
    parser.add_argument("--content", required=True, help="Text content or path to text file")
    parser.add_argument("--subtitle", default="Antigravity AI Document", help="Subtitle")
    
    args = parser.parse_args()
    
    content_text = args.content
    if os.path.isfile(args.content):
        with open(args.content, "r", encoding="utf-8") as f:
            content_text = f.read()

    pdf_file = create_pdf(args.out, args.title, content_text, args.subtitle)
    print(f"SUCCESS: {pdf_file}")
