"""
PDF Generator Utility for WhatsApp Antigravity Bot
Creates clean, professional, publication-quality PDFs from text or markdown prompts.
"""

import sys
import os
import argparse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle

def create_pdf(output_path: str, title: str, content: str, subtitle: str = "Generated by Antigravity AI"):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )

    heading_style = ParagraphStyle(
        'DocHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )

    bullet_style = ParagraphStyle(
        'DocBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        leftIndent=15,
        spaceAfter=4
    )

    story = []

    # Title & Subtitle
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(subtitle, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284C7'), spaceAfter=15))

    # Parse and add content
    lines = content.split('\n')
    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            story.append(Spacer(1, 6))
            continue
        
        # Clean line for XML escaping
        safe_line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        
        if line.startswith('### ') or line.startswith('## ') or line.startswith('# '):
            clean_head = safe_line.lstrip('#').strip()
            story.append(Paragraph(f"<b>{clean_head}</b>", heading_style))
        elif line.startswith('- ') or line.startswith('* ') or line.startswith('• '):
            clean_bullet = safe_line[2:].strip()
            story.append(Paragraph(f"• {clean_bullet}", bullet_style))
        else:
            story.append(Paragraph(safe_line, body_style))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=8))
    footer_text = "Generated automatically for you by Antigravity WhatsApp Engine."
    story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontName='Helvetica-Oblique', fontSize=8, textColor=colors.HexColor('#94A3B8'), alignment=1)))

    doc.build(story)
    return output_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate PDF document")
    parser.add_argument("--out", required=True, help="Output PDF file path")
    parser.add_argument("--title", required=True, help="Title of the PDF")
    parser.add_argument("--content", required=True, help="Text content or path to text file")
    parser.add_argument("--subtitle", default="Antigravity AI Document", help="Subtitle")
    
    args = parser.parse_args()
    
    content_text = args.content
    if os.path.isfile(args.content):
        with open(args.content, "r", encoding="utf-8") as f:
            content_text = f.read()

    pdf_file = create_pdf(args.out, args.title, content_text, args.subtitle)
    print(f"SUCCESS: {pdf_file}")
