"""
PDF Generator Utility for WhatsApp Antigravity Bot
Creates clean, professional, publication-quality PDFs from text or markdown prompts.
"""

import sys
import os
import argparse
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Register a font with wide Unicode support if available
FONT_NAME = 'Helvetica'
BOLD_FONT_NAME = 'Helvetica-Bold'

for p in [
    '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    'C:/Windows/Fonts/arial.ttf',
    'C:/Windows/Fonts/segoeui.ttf'
]:
    if os.path.exists(p):
        try:
            pdfmetrics.registerFont(TTFont('UniversalFont', p))
            FONT_NAME = 'UniversalFont'
            BOLD_FONT_NAME = 'UniversalFont'
            break
        except Exception:
            pass

def clean_text_for_font(text: str, font: str) -> str:
    if font == 'Helvetica' or font == 'Helvetica-Bold':
        # Remove characters outside latin-1 to avoid ReportLab encoding crash
        return text.encode('latin-1', 'replace').decode('latin-1')
    return text

def create_pdf(output_path: str, title: str, content: str, subtitle: str = "Generated by Antigravity AI"):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=BOLD_FONT_NAME,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )

    h1_style = ParagraphStyle(
        'DocH1',
        parent=styles['Heading1'],
        fontName=BOLD_FONT_NAME,
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=14,
        spaceAfter=6
    )

    h2_style = ParagraphStyle(
        'DocH2',
        parent=styles['Heading2'],
        fontName=BOLD_FONT_NAME,
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=10,
        spaceAfter=4
    )

    h3_style = ParagraphStyle(
        'DocH3',
        parent=styles['Heading3'],
        fontName=BOLD_FONT_NAME,
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#0284C7'),
        spaceBefore=8,
        spaceAfter=3
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'DocBullet',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#334155'),
        leftIndent=15,
        spaceAfter=4
    )

    callout_style = ParagraphStyle(
        'DocCallout',
        parent=styles['Normal'],
        fontName=FONT_NAME,
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#1E293B'),
        leftIndent=15,
        spaceBefore=4,
        spaceAfter=6
    )

    import re

    def format_inline_markdown(text: str) -> str:
        # XML escape first
        t = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        # Bold: **bold**
        t = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', t)
        # Italic: *italic*
        t = re.sub(r'(?<!\*)\*(?!\*)(.*?)\*', r'<i>\1</i>', t)
        # Inline code: `code`
        t = re.sub(r'`(.*?)`', r'<font face="Courier" color="#0369a1">\1</font>', t)
        return t

    story = []

    # Title & Subtitle
    safe_title = clean_text_for_font(title, BOLD_FONT_NAME)
    safe_sub = clean_text_for_font(subtitle, FONT_NAME)
    story.append(Paragraph(safe_title, title_style))
    story.append(Paragraph(safe_sub, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284C7'), spaceAfter=12))

    # Parse content lines
    lines = content.split('\n')
    i = 0
    total_lines = len(lines)

    while i < total_lines:
        line = lines[i].strip()
        if not line:
            story.append(Spacer(1, 4))
            i += 1
            continue

        clean_line = clean_text_for_font(line, FONT_NAME)

        # Check for Markdown Table: starts and ends with |
        if clean_line.startswith('|') and clean_line.endswith('|'):
            table_rows = []
            while i < total_lines and lines[i].strip().startswith('|') and lines[i].strip().endswith('|'):
                cur_row = lines[i].strip()
                # Ignore separator lines like |---|---|
                if not re.match(r'^\|[\s\-:|]+\|$', cur_row):
                    cols = [c.strip() for c in cur_row.strip('|').split('|')]
                    formatted_cols = [Paragraph(format_inline_markdown(clean_text_for_font(c, FONT_NAME)), body_style) for c in cols]
                    table_rows.append(formatted_cols)
                i += 1
            
            if table_rows:
                try:
                    t = Table(table_rows, colWidths=None)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
                        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E1')),
                        ('TOPPADDING', (0, 0), (-1, -1), 4),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 6))
                except Exception:
                    pass
            continue

        # Headings
        if clean_line.startswith('# '):
            story.append(Paragraph(format_inline_markdown(clean_line[2:].strip()), h1_style))
        elif clean_line.startswith('## '):
            story.append(Paragraph(format_inline_markdown(clean_line[3:].strip()), h2_style))
        elif clean_line.startswith('### '):
            story.append(Paragraph(format_inline_markdown(clean_line[4:].strip()), h3_style))
        elif clean_line.startswith('#### '):
            story.append(Paragraph(f"<b>{format_inline_markdown(clean_line[5:].strip())}</b>", body_style))
        # Bullet points
        elif clean_line.startswith('- ') or clean_line.startswith('* ') or clean_line.startswith('• '):
            clean_bullet = clean_line[2:].strip()
            story.append(Paragraph(f"• {format_inline_markdown(clean_bullet)}", bullet_style))
        # Numbered lists like 1. 2.
        elif re.match(r'^\d+\.\s', clean_line):
            story.append(Paragraph(format_inline_markdown(clean_line), bullet_style))
        # Callout block: > Note / > Tip
        elif clean_line.startswith('> '):
            callout_text = clean_line[2:].strip()
            story.append(Paragraph(f"💡 <i>{format_inline_markdown(callout_text)}</i>", callout_style))
        else:
            story.append(Paragraph(format_inline_markdown(clean_line), body_style))

        i += 1

    story.append(Spacer(1, 15))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceAfter=8))
    footer_text = "Generated automatically by Antigravity AI Engine."
    story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontName=FONT_NAME, fontSize=8, textColor=colors.HexColor('#94A3B8'), alignment=1)))

    doc.build(story)
    return output_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate PDF document")
    parser.add_argument("--out", required=True, help="Output PDF file path")
    parser.add_argument("--title", required=True, help="Title of the PDF")
    parser.add_argument("--content", required=True, help="Text content or path to text file")
    parser.add_argument("--subtitle", default="Antigravity AI Document", help="Subtitle")
    
    args = parser.parse_args()
    
    content_text = args.content
    if os.path.isfile(args.content):
        with open(args.content, "r", encoding="utf-8") as f:
            content_text = f.read()

    pdf_file = create_pdf(args.out, args.title, content_text, args.subtitle)
    print(f"SUCCESS: {pdf_file}")
